const AUTH = '@auth';

export const NOTIFICATIONS_ERROR = 'NOTIFICATIONS_ERROR';
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS';

export const AUTH_LOGIN_LOAD = `${AUTH}/LOGIN_LOAD`;
export const AUTH_LOGIN_SUCCESS = `${AUTH}/LOGIN_SUCCESS`;
export const AUTH_ERROR = `${AUTH}/ERROR`;
export const AUTH_IS_LOADING = `${AUTH}/IS_LOADING`;
export const AUTH_LOGOUT = `${AUTH}/LOGOUT`;

export const AUTH_SIGN_UP_LOAD = `${AUTH}/SIGN_UP_LOAD`;
export const AUTH_SIGN_UP_SUCCESS = `${AUTH}/SIGN_UP_SUCCESS`;
export const AUTH_FORGOT_PASSWORD = `${AUTH}/FORGOT_PASSWORD`;
